### ISSUE TITLE
Feature Request: Allow state toggling of checkboxes when viewing a file

### ISSUE THREAD

**Issue by drjaska** [billthefarmer/notes#46]
Hi, I'm loving this app thus far but I've found checkboxes to be slightly clumsy in it.

Currently there are checkboxes in markdown implemented via
```
- [ ]
- [x]
```
which are very nice for incremental tasks in a list but editing them on a mobile touch screen in the editing screen is very tedious and I've yet to find a way around it.

I'd like to propose a feature where they can be tapped in preview screen to toggle their state between unmarked and marked. Other methods are acceptable too if you don't like my suggestion, anything is better than nothing. =)

**Comment by drjaska** [comment]
Derailing CSS question about checkboxes:  Is it possible to have the checked :heavy_check_mark: checkboxes have a colored e.g. green background so they clearly stand out?

**Comment by drjaska** [comment]
> Making the task list interactive is beyond the scope of this project.

Could you elaborate this a bit more? Is the input handler unable to know if a checkbox is pressed and send a file editing signal forwards? I didn't understand if you explained this.

<details>
<summary>Derailing CSS Answer: </summary>

I had massive help from a friend with the groundwork for this but I managed to create these:

![image](https://github.com/billthefarmer/notes/assets/88596812/c7d9de57-fdea-4a13-957c-fb5dcba6aa40)

```css
[type="checkbox"] {
  appearance: none;
  background-color: gray;
  border-radius: 6px;
  cursor: pointer;
  user-select: none;
  width: 2.5em;
  height: 2.5em;
  position: relative;
  top: 1em;
}

[type="checkbox"]:checked {
  background-color: lime;
  background-image:
    linear-gradient( 50deg, #0000 12%, #FFFf 0, #FFFf 20%, #0000 0
),
    linear-gradient(-55deg, #0000 36%, #FFFf 0, #FFFf 45%, #0000 0
);
  background-position: 50% 50%;
  background-repeat: no-repeat;
  background-size: 75% 75%;
}
```

</details>
